version: "3.9"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pydb
      MYSQL_USER: ekta
      MYSQL_PASSWORD: ekta
    ports:
      - "3307:3306"
  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: example_user
      DB_PASSWORD: example_password
      DB_NAME: example_db
    ports:
      - "5000:5000"
